name: Release
on:
  workflow_run:
    workflows: ["Test"]
    branches: [master]
    types:
      - completed
jobs:
  # build_wheels:
  #   name: Build wheels on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install wheel
        run: python -m pip install wheel==0.38.4 setuptools==65.5.1 setuptools_scm[toml]==7.0.5
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.2
      - name: Build wheels
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          make
          python -m cibuildwheel --output-dir wheelhouse
      - name: Build source distribution
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          make
          python setup.py sdist
      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse/
